### ISSUE TITLE
direction option closes the game with Optifine

### ISSUE THREAD

**Issue by merko83** [VsnGamer/ElevatorMod#122]
As I had mentioned, the error occurs when activating the elevator direction option with Optifine installed. With Rubidium installed it only happens occasionally. When this error happens, it closes the game of the entire player with Optifine that is within the mca of the map, whoever does not have it remains in the game.

minecraft version: 1.19.2
forge version: 43.2.21
Optifine version: OptiFine_1.19.2_HD_U_H9

How to reproduce the error: having Optifine installed, enter the game to the elevator block option and activate the direction box

[crash-2023-11-05_19.06.34-client.txt](https://github.com/VsnGamer/ElevatorMod/files/13260476/crash-2023-11-05_19.06.34-client.txt)

Un saludo, gracias.

**Comment by VsnGamer** [comment]
Generally Optifine has issues when used with other mods.
However you are using OptiFine HD U H9 which on the website says it's compatible with forge Forge 43.1.1.
You can try to update it to HD U I2 since you are running forge 42.2.21.

You can also try using [Embeddium](https://github.com/embeddedt/embeddium) which seems to have less compatibility issues.

**Comment by merko83** [comment]
Indeed, with the Optifine HD U I2 update the error does NOT occur again. Thank you very much for the solution.
