### ISSUE TITLE
Crash in server 1.15.1

### ISSUE THREAD

**Issue by jrjespersen** [VsnGamer/ElevatorMod#50]
I get a crash when trying to load this mod in server 1.15.1.

Crash: https://pastebin.com/CYUWXezt
Minecraft version 1.15.1
Forge version: forge-1.15.1-30.0.51

No other mods loaded

**Comment by VsnGamer** [comment]
The [last](https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.15.1-30.0.51/forge-1.15.1-30.0.51-changelog.txt) forge for 1.15.1 changed the name of a class(ModConfigEvent.ConfigReloading to ModConfigEvent.Reloading) and because the mod was compiled with the 30.0.7 it's trying to refer at the old class name.

This is, of course, fxed in the 1.15.2 version of the mod, and because 1.15.1 is no longer suported by forge there is not really a reason for using that version.

If you really need to use 1.15.1 I'll release a quick fix but consider to move on to 1.15.2.

**Comment by jrjespersen** [comment]
I don't really "need" it - this is for a family mod server. The other mods I'm using haven't all released 1.15.2 versions yet (and unfortunately, a few of the mods require the 30.0.51 version of Forge.
I'm waiting for when I can go to 1.15.2 and can be patient. I really like this mod as it's one of the simpler mods (as in not requiring a huge mod or system) for teleportation.

**Comment by VsnGamer** [comment]
Please test new file, thanks.
